// CoRayLib.idl
//

import "oaidl.idl";
import "ocidl.idl";


[
    object,
    dual,
    uuid(3961290B-48A8-4ABD-8F8F-7EC13E936E49),
    pointer_default(unique)
]
interface IRayLibColor : IDispatch
{
    [id(1), propget] HRESULT r([out, retval] long* pval);
    [id(1), propput] HRESULT r([in] long val);
    [id(2), propget] HRESULT g([out, retval] long* pval);
    [id(2), propput] HRESULT g([in] long val);
    [id(3), propget] HRESULT b([out, retval] long* pval);
    [id(3), propput] HRESULT b([in] long val);
    [id(4), propget] HRESULT a([out, retval] long* pval);
    [id(4), propput] HRESULT a([in] long val);
}

[
    object,
    dual,
    uuid(55BECA04-F6BB-4A63-8B7C-D5DC1952A596),
    pointer_default(unique)
]
interface IRayLibVector2 : IDispatch
{
    [id(1), propget] HRESULT x([out, retval] float* pval);
    [id(1), propput] HRESULT x([in] float val);
    [id(2), propget] HRESULT y([out, retval] float* pval);
    [id(2), propput] HRESULT y([in] float val);
}

[
    object,
    dual,
    uuid(BD799537-5792-4130-8E39-3AFE127C534D),
    pointer_default(unique)
]
interface IRayLibVector3 : IDispatch
{
    [id(1), propget] HRESULT x([out, retval] float* pval);
    [id(1), propput] HRESULT x([in] float val);
    [id(2), propget] HRESULT y([out, retval] float* pval);
    [id(2), propput] HRESULT y([in] float val);
    [id(3), propget] HRESULT z([out, retval] float* pval);
    [id(3), propput] HRESULT z([in] float val);
}

[
    object,
    dual,
    uuid(743C6255-B2F4-465C-B76C-818843D0ECAC),
    pointer_default(unique)
]
interface IRayLibVector4 : IDispatch
{
    [id(1), propget] HRESULT x([out, retval] float* pval);
    [id(1), propput] HRESULT x([in] float val);
    [id(2), propget] HRESULT y([out, retval] float* pval);
    [id(2), propput] HRESULT y([in] float val);
    [id(3), propget] HRESULT z([out, retval] float* pval);
    [id(3), propput] HRESULT z([in] float val);
    [id(4), propget] HRESULT w([out, retval] float* pval);
    [id(4), propput] HRESULT w([in] float val);
}

[
    object,
    dual,
    uuid(1D4315C0-5CD8-4796-A81E-C66D5FC60592),
    pointer_default(unique)
]
interface IRayLibRectangle : IDispatch
{
    [id(1), propget] HRESULT x([out, retval] float* pval);
    [id(1), propput] HRESULT x([in] float val);
    [id(2), propget] HRESULT y([out, retval] float* pval);
    [id(2), propput] HRESULT y([in] float val);
    [id(3), propget] HRESULT width([out, retval] float* pval);
    [id(3), propput] HRESULT width([in] float val);
    [id(4), propget] HRESULT height([out, retval] float* pval);
    [id(4), propput] HRESULT height([in] float val);
}

[
    object,
    dual,
    uuid(4DD3E748-D4A3-46B2-9DAF-61A6BDFA8578),
    pointer_default(unique)
]
interface IRayLibTexture : IDispatch
{
    [id(1), propget] HRESULT id([out, retval] long* pval);
    [id(1), propput] HRESULT id([in] long val);
    [id(2), propget] HRESULT width([out, retval] long* pval);
    [id(2), propput] HRESULT width([in] long val);
    [id(3), propget] HRESULT height([out, retval] long* pval);
    [id(3), propput] HRESULT height([in] long val);
    [id(4), propget] HRESULT mipmaps([out, retval] long* pval);
    [id(4), propput] HRESULT mipmaps([in] long val);
    [id(5), propget] HRESULT format([out, retval] long* pval);
    [id(5), propput] HRESULT format([in] long val);
}

[
    object,
    dual,
    uuid(C1A9BAB0-096C-40F7-8C98-761AAE69BD25),
    pointer_default(unique)
]
interface IRayLibRenderTexture : IDispatch
{
    [id(1), propget] HRESULT id([out, retval] long* pval);
    [id(1), propput] HRESULT id([in] long val);
    [id(2), propget] HRESULT texture([out, retval] IRayLibTexture** pval);
    [id(2), propputref] HRESULT texture([in] IRayLibTexture* val);
    [id(3), propget] HRESULT depth([out, retval] IRayLibTexture** pval);
    [id(3), propputref] HRESULT depth([in] IRayLibTexture* val);
}

[
    object,
    dual,
    uuid(2FC4840E-89C1-4AF9-BF6A-D6D4EA0FDC0B),
    pointer_default(unique)
]
interface IRayLibMatrix : IDispatch
{
    [id(1), propget] HRESULT m0([out, retval] float* pval);
    [id(1), propput] HRESULT m0([in] float val);
    [id(2), propget] HRESULT m1([out, retval] float* pval);
    [id(2), propput] HRESULT m1([in] float val);
    [id(3), propget] HRESULT m2([out, retval] float* pval);
    [id(3), propput] HRESULT m2([in] float val);
    [id(4), propget] HRESULT m3([out, retval] float* pval);
    [id(4), propput] HRESULT m3([in] float val);
    [id(5), propget] HRESULT m4([out, retval] float* pval);
    [id(5), propput] HRESULT m4([in] float val);
    [id(6), propget] HRESULT m5([out, retval] float* pval);
    [id(6), propput] HRESULT m5([in] float val);
    [id(7), propget] HRESULT m6([out, retval] float* pval);
    [id(7), propput] HRESULT m6([in] float val);
    [id(8), propget] HRESULT m7([out, retval] float* pval);
    [id(8), propput] HRESULT m7([in] float val);
    [id(9), propget] HRESULT m8([out, retval] float* pval);
    [id(9), propput] HRESULT m8([in] float val);
    [id(10), propget] HRESULT m9([out, retval] float* pval);
    [id(10), propput] HRESULT m9([in] float val);
    [id(11), propget] HRESULT m10([out, retval] float* pval);
    [id(11), propput] HRESULT m10([in] float val);
    [id(12), propget] HRESULT m11([out, retval] float* pval);
    [id(12), propput] HRESULT m11([in] float val);
    [id(13), propget] HRESULT m12([out, retval] float* pval);
    [id(13), propput] HRESULT m12([in] float val);
    [id(14), propget] HRESULT m13([out, retval] float* pval);
    [id(14), propput] HRESULT m13([in] float val);
    [id(15), propget] HRESULT m14([out, retval] float* pval);
    [id(15), propput] HRESULT m14([in] float val);
    [id(16), propget] HRESULT m15([out, retval] float* pval);
    [id(16), propput] HRESULT m15([in] float val);
}

[
    object,
    dual,
    uuid(D1A4E153-B526-4CFA-975C-DE8365B79DD4),
    pointer_default(unique)
]
interface IRayLibCamera2D : IDispatch
{
    [id(1), propget] HRESULT offset([out, retval] IRayLibVector2** pval);
    [id(1), propputref] HRESULT offset([in] IRayLibVector2* val);
    [id(2), propget] HRESULT target([out, retval] IRayLibVector2** pval);
    [id(2), propputref] HRESULT target([in] IRayLibVector2* val);
    [id(3), propget] HRESULT rotation([out, retval] float* pval);
    [id(3), propput] HRESULT rotation([in] float val);
    [id(4), propget] HRESULT zoom([out, retval] float* pval);
    [id(4), propput] HRESULT zoom([in] float val);
}

[
    object,
    dual,
    uuid(EB66F0C5-719C-4352-B897-2264361832F5),
    pointer_default(unique)
]
interface IRayLibCamera3D : IDispatch
{
    [id(1), propget] HRESULT position([out, retval] IRayLibVector3** pval);
    [id(1), propputref] HRESULT position([in] IRayLibVector3* val);
    [id(2), propget] HRESULT target([out, retval] IRayLibVector3** pval);
    [id(2), propputref] HRESULT target([in] IRayLibVector3* val);
    [id(3), propget] HRESULT up([out, retval] IRayLibVector3** pval);
    [id(3), propputref] HRESULT up([in] IRayLibVector3* val);
    [id(4), propget] HRESULT fovy([out, retval] float* pval);
    [id(4), propput] HRESULT fovy([in] float val);
    [id(5), propget] HRESULT projection([out, retval] long* pval);
    [id(5), propput] HRESULT projection([in] long val);
}

[
    object,
    dual,
    uuid(E1EB9824-2B86-4996-900C-946956A567BA),
    pointer_default(unique)
]
interface IRayLibRay : IDispatch
{
    [id(1), propget] HRESULT position([out, retval] IRayLibVector3** pval);
    [id(1), propputref] HRESULT position([in] IRayLibVector3* val);
    [id(2), propget] HRESULT direction([out, retval] IRayLibVector3** pval);
    [id(2), propputref] HRESULT direction([in] IRayLibVector3* val);
}

[
    object,
    dual,
    uuid(05F3B287-43B8-4487-A5F1-670511134CFD),
    pointer_default(unique)
]
interface IRayLibBoundingBox : IDispatch
{
    [id(1), propget] HRESULT min([out, retval] IRayLibVector3** pval);
    [id(1), propputref] HRESULT min([in] IRayLibVector3* val);
    [id(2), propget] HRESULT max([out, retval] IRayLibVector3** pval);
    [id(2), propputref] HRESULT max([in] IRayLibVector3* val);
}

[
    object,
    dual,
    uuid(E6DCC358-99F0-4285-B58E-8DC1C4BA1077),
    pointer_default(unique)
]
interface IRayLibRayCollision : IDispatch
{
    [id(1), propget] HRESULT hit([out, retval] VARIANT_BOOL* pval);
    [id(1), propput] HRESULT hit([in] VARIANT_BOOL val);
    [id(2), propget] HRESULT distance([out, retval] float* pval);
    [id(2), propput] HRESULT distance([in] float val);
    [id(3), propget] HRESULT point([out, retval] IRayLibVector3** pval);
    [id(3), propputref] HRESULT point([in] IRayLibVector3* val);
    [id(4), propget] HRESULT normal([out, retval] IRayLibVector3** pval);
    [id(4), propputref] HRESULT normal([in] IRayLibVector3* val);
}

[
    object,
    dual,
    uuid(BA8623BB-26BE-4D50-94BE-067C1B6785AC),
    pointer_default(unique)
]
interface IRayLib : IDispatch
{
    //////////////////////////////////////////////
    // Module: RCORE

    // Window-related functions
    [id(1)] HRESULT InitWindow([in] long width, [in] long height, [in] BSTR title);
    [id(2)] HRESULT CloseWindow(void);
    [id(3)] HRESULT WindowShouldClose([out, retval] VARIANT_BOOL* pRetVal);
    [id(4)] HRESULT IsWindowReady([out, retval] VARIANT_BOOL* pRetVal);
    [id(5)] HRESULT IsWindowFullscreen([out, retval] VARIANT_BOOL* pRetVal);
    [id(6)] HRESULT IsWindowHidden([out, retval] VARIANT_BOOL* pRetVal);
    [id(7)] HRESULT IsWindowMinimized([out, retval] VARIANT_BOOL* pRetVal);
    [id(8)] HRESULT IsWindowMaximized([out, retval] VARIANT_BOOL* pRetVal);
    [id(9)] HRESULT IsWindowFocused([out, retval] VARIANT_BOOL* pRetVal);
    [id(10)] HRESULT IsWindowResized([out, retval] VARIANT_BOOL* pRetVal);
    [id(11)] HRESULT IsWindowState([in] long flag, [out, retval] VARIANT_BOOL* pRetVal);
    [id(12)] HRESULT SetWindowState([in] long flags);
    [id(13)] HRESULT ClearWindowState([in] long flags);
    [id(14)] HRESULT ToggleFullscreen(void);
    [id(15)] HRESULT ToggleBorderlessWindowed(void);
    [id(16)] HRESULT MaximizeWindow(void);
    [id(17)] HRESULT MinimizeWindow(void);
    [id(18)] HRESULT RestoreWindow(void);
//	[id(19)] HRESULT SetWindowIcon(Image image);
//	[id(20)] HRESULT SetWindowIcons(Image* images, int count);
    [id(21)] HRESULT SetWindowTitle([in] BSTR title);
    [id(22)] HRESULT SetWindowPosition([in] long x, [in] long y);
    [id(23)] HRESULT SetWindowMonitor([in] long monitor);
    [id(24)] HRESULT SetWindowMinSize([in] long width, [in] long height);
    [id(25)] HRESULT SetWindowMaxSize([in] long width, [in] long height);
    [id(26)] HRESULT SetWindowSize([in] long width, [in] long height);
    [id(27)] HRESULT SetWindowOpacity([in] float opacity);
    [id(28)] HRESULT SetWindowFocused(void);
//  [id(29)] HRESULT GetWindowHandle([out, retval] * pRetVal);
    [id(30)] HRESULT GetScreenWidth([out, retval] long* pReVal);
    [id(31)] HRESULT GetScreenHeight([out, retval] long* pReVal);
    [id(32)] HRESULT GetRenderWidth([out, retval] long* pReVal);
    [id(33)] HRESULT GetRenderHeight([out, retval] long* pReVal);
    [id(34)] HRESULT GetMonitorCount([out, retval] long* pReVal);
    [id(35)] HRESULT GetCurrentMonitor([out, retval] long* pReVal);
    [id(36)] HRESULT GetMonitorPosition([in] long monitor, [out, retval] IRayLibVector2** pRetVal);
    [id(37)] HRESULT GetMonitorWidth([in] long monitor, [out, retval] long* pRetVal);
    [id(38)] HRESULT GetMonitorHeight([in] long monitor, [out, retval] long* pRetVal);
    [id(39)] HRESULT GetMonitorPhysicalWidth([in] long monitor, [out, retval] long* pRetVal);
    [id(40)] HRESULT GetMonitorPhysicalHeight([in] long monitor, [out, retval] long* pRetVal);
    [id(41)] HRESULT GetMonitorRefreshRate([in] long monitor, [out, retval] long* pRetVal);
    [id(42)] HRESULT GetWindowPosition([out, retval] IRayLibVector2** pRetVal);
    [id(43)] HRESULT GetWindowScaleDPI([out, retval] IRayLibVector2** pRetVal);
    [id(44)] HRESULT GetMonitorName([in] long monitor, [out, retval] BSTR* pRetVal);
    [id(45)] HRESULT SetClipboardText([in] BSTR text);
    [id(46)] HRESULT GetClipboardText([out, retval] BSTR* pRetVal);
 //	[id(47)] HRESULT Image GetClipboardImage(void);
    [id(48)] HRESULT EnableEventWaiting(void);
    [id(49)] HRESULT DisableEventWaiting(void);

    // Cursor-related functions
    [id(50)] HRESULT ShowCursor(void);
    [id(51)] HRESULT HideCursor(void);
    [id(52)] HRESULT IsCursorHidden([out, retval] VARIANT_BOOL* pRetVal);
    [id(53)] HRESULT EnableCursor(void);
    [id(54)] HRESULT DisableCursor(void);
    [id(55)] HRESULT IsCursorOnScreen([out, retval] VARIANT_BOOL* pRetVal);

    // Drawing-related functions
    [id(70)] HRESULT ClearBackground([in] IRayLibColor* color);
    [id(71)] HRESULT BeginDrawing(void);
    [id(72)] HRESULT EndDrawing(void);
    [id(73)] HRESULT BeginMode2D([in] IRayLibCamera2D* camera);
    [id(74)] HRESULT EndMode2D(void);
    [id(75)] HRESULT BeginMode3D([in] IRayLibCamera3D* camera);
    [id(76)] HRESULT EndMode3D(void);

    [id(81)] HRESULT BeginBlendMode([in] long mode);
    [id(82)] HRESULT EndBlendMode(void);
    [id(83)] HRESULT BeginScissorMode([in] long x, [in] long y, [in] long width, [in] long height);
    [id(84)] HRESULT EndScissorMode(void);

    // VR stereo config functions for VR simulator

    // Shader management functions

    // Screen-space-related functions
    [id(130)] HRESULT GetScreenToWorldRay([in] IRayLibVector2* position, [in] IRayLibCamera3D* camera, [out, retval] IRayLibRay** pRetVal);
    [id(131)] HRESULT GetScreenToWorldRayEx([in] IRayLibVector2* position, [in] IRayLibCamera3D* camera, [in] long width, [in] long height, [out, retval] IRayLibRay** pRetVal);
    [id(132)] HRESULT GetWorldToScreen([in] IRayLibVector3* position, [in] IRayLibCamera3D* camera, [out, retval] IRayLibVector2** pRetVal);
    [id(133)] HRESULT GetWorldToScreenEx([in] IRayLibVector3* position, [in] IRayLibCamera3D* camera, [in] long width, [in] long height, [out, retval] IRayLibVector2** pRetVal);
    [id(134)] HRESULT GetWorldToScreen2D([in] IRayLibVector2* position, [in] IRayLibCamera2D* camera, [out, retval] IRayLibVector2** pRetVal);
    [id(135)] HRESULT GetScreenToWorld2D([in] IRayLibVector2* position, [in] IRayLibCamera2D* camera, [out, retval] IRayLibVector2** pRetVal);
    [id(136)] HRESULT GetCameraMatrix([in] IRayLibCamera3D* camera, [out, retval] IRayLibMatrix** pRetVal);
    [id(137)] HRESULT GetCameraMatrix2D([in] IRayLibCamera2D* camera, [out, retval] IRayLibMatrix** pRetVal);

    // Timing-related functions
    [id(140)] HRESULT SetTargetFPS([in] long fps);
    [id(141)] HRESULT GetFrameTime([out, retval] float* pRetVal);
    [id(142)] HRESULT GetTime([out, retval] double* pRetVal);
    [id(143)] HRESULT GetFPS([out, retval] long* pRetVal);

    // Custom frame control functions
    [id(150)] HRESULT SwapScreenBuffer(void);
    [id(151)] HRESULT PollInputEvents(void);
    [id(152)] HRESULT WaitTime([in] double seconds);

    // Random values generation functions
    [id(160)] HRESULT SetRandomSeed([in] long seed);
    [id(161)] HRESULT GetRandomValue([in] long min, [in] long max, [out, retval] long* pRetVal);

    // Misc. functions
    [id(170)] HRESULT TakeScreenshot([in] BSTR fileName);
    [id(171)] HRESULT SetConfigFlags([in] long flags);
    [id(172)] HRESULT OpenURL([in] BSTR url);

    // Logging system
    [id(173)] HRESULT SetTraceLogLevel([in] long logLevel);

    // Memory management, using internal allocators

    // File system management functions

    // File access custom callbacks

    // Compression/Encoding functionality

    // Automation events functionality

    // Input-related functions: keyboard
    [id(330)] HRESULT IsKeyPressed([in] long key, [out, retval] VARIANT_BOOL* pRetVal);
    [id(331)] HRESULT IsKeyPressedRepeat([in] long key, [out, retval] VARIANT_BOOL* pRetVal);
    [id(332)] HRESULT IsKeyDown([in] long key, [out, retval] VARIANT_BOOL* pRetVal);
    [id(333)] HRESULT IsKeyReleased([in] long key, [out, retval] VARIANT_BOOL* pRetVal);
    [id(334)] HRESULT IsKeyUp([in] long key, [out, retval] VARIANT_BOOL* pRetVal);
    [id(335)] HRESULT GetKeyPressed([out, retval] long* pRetVal);
    [id(336)] HRESULT GetCharPressed([out, retval] long* pRetVal);
    [id(337)] HRESULT SetExitKey([in] long key);

    // Input-related functions: gamepads
    [id(338)] HRESULT IsGamepadAvailable([in] long gamepad, [out, retval] VARIANT_BOOL* pRetVal);
    [id(339)] HRESULT GetGamepadName([in] long gamepad, [out, retval] BSTR* pRetVal);
    [id(340)] HRESULT IsGamepadButtonPressed([in] long gamepad, [in] long button, [out, retval] VARIANT_BOOL* pRetVal);
    [id(341)] HRESULT IsGamepadButtonDown([in] long gamepad, [in] long button, [out, retval] VARIANT_BOOL* pRetVal);
    [id(342)] HRESULT IsGamepadButtonReleased([in] long gamepad, [in] long button, [out, retval] VARIANT_BOOL* pRetVal);
    [id(343)] HRESULT IsGamepadButtonUp([in] long gamepad, [in] long button, [out, retval] VARIANT_BOOL* pRetVal);
    [id(344)] HRESULT GetGamepadButtonPressed([out, retval] long* pRetVal);
    [id(345)] HRESULT GetGamepadAxisCount([in] long gamepad, [out, retval] long* pRetVal);
    [id(346)] HRESULT GetGamepadAxisMovement([in] long gamepad, [in] long axis, [out, retval] float* pRetVal);
    [id(347)] HRESULT SetGamepadMappings([in] BSTR mappings, [out, retval] long* pRetVal);
    [id(348)] HRESULT SetGamepadVibration([in] long gamepad, [in] float leftMotor, [in] float rightMotor, [in] float duration);

    // Input-related functions: mouse
    [id(360)] HRESULT IsMouseButtonPressed([in] long button, [out, retval] VARIANT_BOOL* pRetVal);
    [id(361)] HRESULT IsMouseButtonDown([in] long button, [out, retval] VARIANT_BOOL* pRetVal);
    [id(362)] HRESULT IsMouseButtonReleased([in] long button, [out, retval] VARIANT_BOOL* pRetVal);
    [id(363)] HRESULT IsMouseButtonUp([in] long button, [out, retval] VARIANT_BOOL* pRetVal);
    [id(364)] HRESULT GetMouseX([out, retval] long* pRetVal);
    [id(365)] HRESULT GetMouseY([out, retval] long* pRetVal);
    [id(366)] HRESULT GetMousePosition([out, retval] IRayLibVector2** pRetVal);
    [id(367)] HRESULT GetMouseDelta([out, retval] IRayLibVector2** pRetVal);
    [id(368)] HRESULT SetMousePosition([in] long x, [in] long y);
    [id(369)] HRESULT SetMouseOffset([in] long offsetX, [in] long offsetY);
    [id(370)] HRESULT SetMouseScale(float scaleX, float scaleY);
    [id(371)] HRESULT GetMouseWheelMove([out, retval] float* pRetVal);
    [id(372)] HRESULT GetMouseWheelMoveV([out, retval] IRayLibVector2** pRetVal);
    [id(373)] HRESULT SetMouseCursor([in] long cursor);

    // Input-related functions: touch
    [id(374)] HRESULT GetTouchX([out, retval] long* pRetVal);
    [id(375)] HRESULT GetTouchY([out, retval] long* pRetVal);
    [id(376)] HRESULT GetTouchPosition([in] long index, [out, retval] IRayLibVector2** pRetVal);
    [id(377)] HRESULT GetTouchPointId([in] long index, [out, retval] long* pRetVal);
    [id(378)] HRESULT GetTouchPointCount([out, retval] long* pRetVal);

    // Gestures and Touch Handling Functions (Module: rgestures)
    [id(379)] HRESULT SetGesturesEnabled([in] long flags);
    [id(380)] HRESULT IsGestureDetected([in] long gesture, [out, retval] VARIANT_BOOL* pRetVal);
    [id(381)] HRESULT GetGestureDetected([out, retval] long* pRetVal);
    [id(382)] HRESULT GetGestureHoldDuration([out, retval] float* pRetVal);
    [id(383)] HRESULT GetGestureDragVector([out, retval] IRayLibVector2** pRetVal);
    [id(384)] HRESULT GetGestureDragAngle([out, retval] float* pRetVal);
    [id(385)] HRESULT GetGesturePinchVector([out, retval] IRayLibVector2** pRetVal);
    [id(386)] HRESULT GetGesturePinchAngle([out, retval] float* pRetVal);

    // Camera System Functions (Module: rcamera)
    [id(400)] HRESULT UpdateCamera([in] IRayLibCamera3D* camera, [in] long mode);
    [id(401)] HRESULT UpdateCameraPro([in] IRayLibCamera3D* camera, [in] IRayLibVector3* movement, [in] IRayLibVector3* rotation, [in] float zoom);

    //////////////////////////////////////////////
    // Module: RSHAPES

    [id(1002)] HRESULT GetShapesTextureRectangle([out, retval] IRayLibRectangle** pRetVal);

    // Basic shapes drawing functions
    [id(1010)] HRESULT DrawPixel([in] long posX, [in] long posY, [in] IRayLibColor* color);
    [id(1011)] HRESULT DrawPixelV([in] IRayLibVector2* position, [in] IRayLibColor* color);
    [id(1012)] HRESULT DrawLine([in] long startPosX, [in] long startPosY, [in] long endPosX, [in] long endPosY, [in] IRayLibColor* color);
    [id(1013)] HRESULT DrawLineV([in] IRayLibVector2* startPos, [in] IRayLibVector2* endPos, [in] IRayLibColor* color);
    [id(1014)] HRESULT DrawLineEx([in] IRayLibVector2* startPos, [in] IRayLibVector2* endPos, [in] float thick, [in] IRayLibColor* color);

    [id(1016)] HRESULT DrawLineBezier([in] IRayLibVector2* startPos, [in] IRayLibVector2* endPos, [in] float thick, [in] IRayLibColor* color);
    [id(1017)] HRESULT DrawLineDashed([in] IRayLibVector2* startPos, [in] IRayLibVector2* endPos, [in] long dashSize, [in] long spaceSize, [in] IRayLibColor* color);
    [id(1020)] HRESULT DrawCircle([in] long centerX, [in] long centerY, [in] float radius, [in] IRayLibColor* color);
    [id(1021)] HRESULT DrawCircleV([in] IRayLibVector2* center, [in] float radius, [in] IRayLibColor* color);
    [id(1022)] HRESULT DrawCircleGradient([in] IRayLibVector2* center, [in] float radius, [in] IRayLibColor* inner, [in] IRayLibColor* outer);
    [id(1023)] HRESULT DrawCircleSector([in] IRayLibVector2* center, [in] float radius, [in] float startAngle, [in] float endAngle, [in] long segments, [in] IRayLibColor* color);
    [id(1024)] HRESULT DrawCircleSectorLines([in] IRayLibVector2* center, [in] float radius, [in] float startAngle, [in] float endAngle, [in] long segments, [in] IRayLibColor* color);
    [id(1025)] HRESULT DrawCircleLines([in] long centerX, [in] long centerY, [in] float radius, [in] IRayLibColor* color);
    [id(1026)] HRESULT DrawCircleLinesV([in] IRayLibVector2* center, [in] float radius, [in] IRayLibColor* color);

    [id(1040)] HRESULT DrawEllipse([in] long centerX, [in] long centerY, [in] float radiusH, [in] float radiusV, [in] IRayLibColor* color);
    [id(1041)] HRESULT DrawEllipseV([in] IRayLibVector2* center, [in] float radiusH, [in] float radiusV, [in] IRayLibColor* color);
    [id(1042)] HRESULT DrawEllipseLines([in] long centerX, [in] long centerY, [in] float radiusH, [in] float radiusV, [in] IRayLibColor* color);
    [id(1043)] HRESULT DrawEllipseLinesV([in] IRayLibVector2* center, [in] float radiusH, [in] float radiusV, [in] IRayLibColor* color);
    [id(1044)] HRESULT DrawRing([in] IRayLibVector2* center, [in] float innerRadius, [in] float outerRadius, [in] float startAngle, [in] float endAngle, [in] long segments, [in] IRayLibColor* color);
    [id(1045)] HRESULT DrawRingLines([in] IRayLibVector2* center, [in] float innerRadius, [in] float outerRadius, [in] float startAngle, [in] float endAngle, [in] long segments, [in] IRayLibColor* color);

    [id(1050)] HRESULT DrawRectangle([in] long posX, [in] long posY, [in] long width, [in] long height, [in] IRayLibColor* color);
    [id(1051)] HRESULT DrawRectangleV([in] IRayLibVector2* position, [in] IRayLibVector2* size, [in] IRayLibColor* color);
    [id(1052)] HRESULT DrawRectangleRec([in] IRayLibRectangle* rec, [in] IRayLibColor* color);
    [id(1053)] HRESULT DrawRectanglePro([in] IRayLibRectangle* rec, [in] IRayLibVector2* origin, [in] float rotation, [in] IRayLibColor* color);
    [id(1054)] HRESULT DrawRectangleGradientV([in] long posX, [in] long posY, [in] long width, [in] long height, [in] IRayLibColor* top, [in] IRayLibColor* bottom);
    [id(1055)] HRESULT DrawRectangleGradientH([in] long posX, [in] long posY, [in] long width, [in] long height, [in] IRayLibColor* left, [in] IRayLibColor* right);
    [id(1056)] HRESULT DrawRectangleGradientEx([in] IRayLibRectangle* rec, [in] IRayLibColor* topLeft, [in] IRayLibColor* bottomLeft, [in] IRayLibColor* bottomRight, [in] IRayLibColor* topRight);
    [id(1057)] HRESULT DrawRectangleLines([in] long posX, [in] long posY, [in] long width, [in] long height, [in] IRayLibColor* color);
    [id(1058)] HRESULT DrawRectangleLinesEx([in] IRayLibRectangle* rec, [in] float lineThick, [in] IRayLibColor* color);
    [id(1059)] HRESULT DrawRectangleRounded([in] IRayLibRectangle* rec, [in] float roundness, [in] long segments, [in] IRayLibColor* color);
    [id(1060)] HRESULT DrawRectangleRoundedLines([in] IRayLibRectangle* rec, [in] float roundness, [in] long segments, [in] IRayLibColor* color);
    [id(1061)] HRESULT DrawRectangleRoundedLinesEx([in] IRayLibRectangle* rec, [in] float roundness, [in] long segments, [in] float lineThick, [in] IRayLibColor* color);
    [id(1062)] HRESULT DrawTriangle([in] IRayLibVector2* v1, [in] IRayLibVector2* v2, [in] IRayLibVector2* v3, [in] IRayLibColor* color);
    [id(1063)] HRESULT DrawTriangleLines([in] IRayLibVector2* v1, [in] IRayLibVector2* v2, [in] IRayLibVector2* v3, [in] IRayLibColor* color);

    [id(1070)] HRESULT DrawPoly([in] IRayLibVector2* center, [in] long sides, [in] float radius, [in] float rotation, [in] IRayLibColor* color);
    [id(1071)] HRESULT DrawPolyLines([in] IRayLibVector2* center, [in] long sides, [in] float radius, [in] float rotation, [in] IRayLibColor* color);
    [id(1072)] HRESULT DrawPolyLinesEx([in] IRayLibVector2* center, [in] long sides, [in] float radius, [in] float rotation, [in] float lineThick, [in] IRayLibColor* color);

    // Spline segment point evaluation functions, for a given t [0.0f .. 1.0f]
    [id(1080)] HRESULT GetSplinePointLinear([in] IRayLibVector2* startPos, [in] IRayLibVector2* endPos, [in] float t, [out, retval] IRayLibVector2** pRetVal);
    [id(1081)] HRESULT GetSplinePointBasis([in] IRayLibVector2* p1, [in] IRayLibVector2* p2, [in] IRayLibVector2* p3, [in] IRayLibVector2* p4, [in] float t, [out, retval] IRayLibVector2** pRetVal);
    [id(1082)] HRESULT GetSplinePointCatmullRom([in] IRayLibVector2* p1, [in] IRayLibVector2* p2, [in] IRayLibVector2* p3, [in] IRayLibVector2* p4, [in] float t, [out, retval] IRayLibVector2** pRetVal);
    [id(1083)] HRESULT GetSplinePointBezierQuadratic([in] IRayLibVector2* p1, [in] IRayLibVector2* c2, [in] IRayLibVector2* p3, [in] float t, [out, retval] IRayLibVector2** pRetVal);
    [id(1084)] HRESULT GetSplinePointBezierCubic([in] IRayLibVector2* p1, [in] IRayLibVector2* c2, [in] IRayLibVector2* c3, [in] IRayLibVector2* p4, [in] float t, [out, retval] IRayLibVector2** pRetVal);

    // Basic shapes collision detection functions
    [id(1090)] HRESULT CheckCollisionRecs([in] IRayLibRectangle* rec1, [in] IRayLibRectangle* rec2, [out, retval] VARIANT_BOOL* pRetVal);
    [id(1091)] HRESULT CheckCollisionCircles([in] IRayLibVector2* center1, [in] float radius1, [in] IRayLibVector2* center2, [in] float radius2, [out, retval] VARIANT_BOOL* pRetVal);
    [id(1092)] HRESULT CheckCollisionCircleRec([in] IRayLibVector2* center, [in] float radius, [in] IRayLibRectangle* rec, [out, retval] VARIANT_BOOL* pRetVal);
    [id(1093)] HRESULT CheckCollisionCircleLine([in] IRayLibVector2* center, [in] float radius, [in] IRayLibVector2* p1, [in] IRayLibVector2* p2, [out, retval] VARIANT_BOOL* pRetVal);
    [id(1094)] HRESULT CheckCollisionPointRec([in] IRayLibVector2* point, [in] IRayLibRectangle* rec, [out, retval] VARIANT_BOOL* pRetVal);
    [id(1095)] HRESULT CheckCollisionPointCircle([in] IRayLibVector2* point, [in] IRayLibVector2* center, [in] float radius, [out, retval] VARIANT_BOOL* pRetVal);
    [id(1096)] HRESULT CheckCollisionPointTriangle([in] IRayLibVector2* point, [in] IRayLibVector2* p1, [in] IRayLibVector2* p2, [in] IRayLibVector2* p3, [out, retval] VARIANT_BOOL* pRetVal);
    [id(1097)] HRESULT CheckCollisionPointLine([in] IRayLibVector2* point, [in] IRayLibVector2* p1, [in] IRayLibVector2* p2, [in] long threshold, [out, retval] VARIANT_BOOL* pRetVal);

    [id(1100)] HRESULT GetCollisionRec([in] IRayLibRectangle* rec1, [in] IRayLibRectangle* rec2, [out, retval] IRayLibRectangle** pRetVal);


    // Color/pixel related functions
    [id(1200)] HRESULT ColorIsEqual([in] IRayLibColor* col1, [in] IRayLibColor* col2, [out, retval] VARIANT_BOOL* pRetVal);
    [id(1201)] HRESULT Fade([in] IRayLibColor* color, [in] float alpha, [out, retval] IRayLibColor** pRetVal);


    //////////////////////////////////////////////
    // Module: RTEXT

    // Font loading/unloading functions

    // Text drawing functions
    [id(2020)] HRESULT DrawFPS([in] long posX, [in] long posY);
    [id(2021)] HRESULT DrawText([in] BSTR text, [in] long posX, [in] long posY, [in] long fontSize, [in] IRayLibColor* color);

    // Text font info functions
    [id(2040)] HRESULT SetTextLineSpacing([in] long spacing);
    [id(2041)] HRESULT MeasureText([in] BSTR text, [in] long fontSize, [out, retval] long* pRetVal);

    // Text strings management functions (no UTF-8 strings, only byte chars)
    [id(2073)] HRESULT TextIsEqual([in] BSTR text1, [in] BSTR text2, [out, retval] VARIANT_BOOL* pRetVal);
    [id(2074)] HRESULT TextLength([in] BSTR text, [out, retval] long* pRetVal);
    [id(2075), vararg] HRESULT TextFormat([in] BSTR text, [in] SAFEARRAY(VARIANT) args, [out, retval] BSTR* pRetVal);
    [id(2076)] HRESULT TextSubtext([in] BSTR text, [in] long position, [in] long length, [out, retval] BSTR* pRetVal);
    [id(2077)] HRESULT TextRemoveSpaces([in] BSTR text, [out, retval] BSTR* pRetVal);
    [id(2078)] HRESULT GetTextBetween([in] BSTR text, [in] BSTR begin, [in] BSTR end, [out, retval] BSTR* pRetVal);
    [id(2079)] HRESULT TextReplace([in] BSTR text, [in] BSTR search, [in] BSTR replacement, [out, retval] BSTR* pRetVal);
    [id(2080)] HRESULT TextReplaceAlloc([in] BSTR text, [in] BSTR search, [in] BSTR replacement, [out, retval] BSTR* pRetVal);
    [id(2081)] HRESULT TextReplaceBetween([in] BSTR text, [in] BSTR begin, [in] BSTR end, [in] BSTR replacement, [out, retval] BSTR* pRetVal);
    [id(2082)] HRESULT TextReplaceBetweenAlloc([in] BSTR text, [in] BSTR begin, [in] BSTR end, [in] BSTR replacement, [out, retval] BSTR* pRetVal);

    [id(2090)] HRESULT TextFindIndex([in] BSTR text, [in] BSTR search, [out, retval] long* pRetVal);
    [id(2091)] HRESULT TextToUpper([in] BSTR text, [out, retval] BSTR* pRetVal);
    [id(2092)] HRESULT TextToLower([in] BSTR text, [out, retval] BSTR* pRetVal);
    [id(2093)] HRESULT TextToPascal([in] BSTR text, [out, retval] BSTR* pRetVal);
    [id(2094)] HRESULT TextToSnake([in] BSTR text, [out, retval] BSTR* pRetVal);
    [id(2095)] HRESULT TextToCamel([in] BSTR text, [out, retval] BSTR* pRetVal);
    [id(2096)] HRESULT TextToInteger([in] BSTR text, [out, retval] long* pRetVal);
    [id(2097)] HRESULT TextToFloat([in] BSTR text, [out, retval] float* pRetVal);


    //////////////////////////////////////////////
    // Module: RMODELS

    // Basic geometric 3D shapes drawing functions
    [id(3000)] HRESULT DrawLine3D([in] IRayLibVector3* startPos, [in] IRayLibVector3* endPos, [in] IRayLibColor* color);
    [id(3001)] HRESULT DrawPoint3D([in] IRayLibVector3* position, [in] IRayLibColor* color);
    [id(3002)] HRESULT DrawCircle3D([in] IRayLibVector3* center, [in] float radius, [in] IRayLibVector3* rotationAxis, [in] float rotationAngle, [in] IRayLibColor* color);
    [id(3003)] HRESULT DrawTriangle3D([in] IRayLibVector3* v1, [in] IRayLibVector3* v2, [in] IRayLibVector3* v3, [in] IRayLibColor* color);

    [id(3005)] HRESULT DrawCube([in] IRayLibVector3* position, [in] float width, [in] float height, [in] float length, [in] IRayLibColor* color);
    [id(3006)] HRESULT DrawCubeV([in] IRayLibVector3* position, [in] IRayLibVector3* size, [in] IRayLibColor* color);
    [id(3007)] HRESULT DrawCubeWires([in] IRayLibVector3* position, [in] float width, [in] float height, [in] float length, [in] IRayLibColor* color);
    [id(3008)] HRESULT DrawCubeWiresV([in] IRayLibVector3* position, [in] IRayLibVector3* size, [in] IRayLibColor* color);
    [id(3009)] HRESULT DrawSphere([in] IRayLibVector3* centerPos, [in] float radius, [in] IRayLibColor* color);
    [id(3010)] HRESULT DrawSphereEx([in] IRayLibVector3* centerPos, [in] float radius, [in] long rings, [in] long slices, [in] IRayLibColor* color);
    [id(3011)] HRESULT DrawSphereWires([in] IRayLibVector3* centerPos, [in] float radius, [in] long rings, [in] long slices, [in] IRayLibColor* color);
    [id(3012)] HRESULT DrawCylinder([in] IRayLibVector3* position, [in] float radiusTop, [in] float radiusBottom, [in] float height, [in] long slices, [in] IRayLibColor* color);
    [id(3013)] HRESULT DrawCylinderEx([in] IRayLibVector3* startPos, [in] IRayLibVector3* endPos, [in] float startRadius, [in] float endRadius, [in] long sides, [in] IRayLibColor* color);
    [id(3014)] HRESULT DrawCylinderWires([in] IRayLibVector3* position, [in] float radiusTop, [in] float radiusBottom, [in] float height, [in] long slices, [in] IRayLibColor* color);
    [id(3015)] HRESULT DrawCylinderWiresEx([in] IRayLibVector3* startPos, [in] IRayLibVector3* endPos, [in] float startRadius, [in] float endRadius, [in] long sides, [in] IRayLibColor* color);
    [id(3016)] HRESULT DrawCapsule([in] IRayLibVector3* startPos, [in] IRayLibVector3* endPos, [in] float radius, [in] long slices, [in] long rings, [in] IRayLibColor* color);
    [id(3017)] HRESULT DrawCapsuleWires([in] IRayLibVector3* startPos, [in] IRayLibVector3* endPos, [in] float radius, [in] long slices, [in] long rings, [in] IRayLibColor* color);
    [id(3018)] HRESULT DrawPlane([in] IRayLibVector3* centerPos, [in] IRayLibVector2* size, [in] IRayLibColor* color);
    [id(3019)] HRESULT DrawRay([in] IRayLibRay* ray, [in] IRayLibColor* color);
    [id(3020)] HRESULT DrawGrid([in] long slices, [in] float spacing);


    //////////////////////////////////////////////
    // Module: RAUDIO

    // Audio device management functions
    [id(4000)] HRESULT InitAudioDevice(void);
    [id(4001)] HRESULT CloseAudioDevice(void);
    [id(4002)] HRESULT IsAudioDeviceReady([out, retval] VARIANT_BOOL* pRetVal);
    [id(4003)] HRESULT SetMasterVolume([in] float volume);
    [id(4004)] HRESULT GetMasterVolume([out, retval] float* pRetVal);


    //////////////////////////////////////////////
    // CoRayLib helpers
    [id(20000)] HRESULT CreateColor([in] long r, [in] long g, [in] long b, [in] long a, [out, retval] IRayLibColor** pRetVal);
    [id(20001)] HRESULT CreateVector2([in] float x, [in] float y, [out, retval] IRayLibVector2** pRetVal);
    [id(20002)] HRESULT CreateVector3([in] float x, [in] float y, [in] float z, [out, retval] IRayLibVector3** pRetVal);
    [id(20003)] HRESULT CreateVector4([in] float x, [in] float y, [in] float z, [in] float w, [out, retval] IRayLibVector4** pRetVal);
    [id(20004)] HRESULT CreateQuaternion([in] float x, [in] float y, [in] float z, [in] float w, [out, retval] IRayLibVector4** pRetVal);
    [id(20005)] HRESULT CreateRectangle([in] float x, [in] float y, [in] float width, [in] float height, [out, retval] IRayLibRectangle** pRetVal);
    [id(20006)] HRESULT CreateMatrix([out, retval] IRayLibMatrix** pRetVal);
    [id(20007)] HRESULT CreateCamera2D([out, retval] IRayLibCamera2D** pRetVal);
    [id(20008)] HRESULT CreateCamera3D([out, retval] IRayLibCamera3D** pRetVal);
    [id(20009)] HRESULT CreateTexture([out, retval] IRayLibTexture** pRetVal);
    [id(20010)] HRESULT CreateRenderTexture([out, retval] IRayLibRenderTexture** pRetVal);
}

[
    uuid(b3f77c41-38c5-4093-af2b-2b26510faa19),
    version(1.0),
    helpstring("RayLib 1.0 Type Library")
]
library RayLib
{
    importlib("stdole2.tlb");

    interface IRayLib;
    interface IRayLibColor;
    interface IRayLibVector2;
    interface IRayLibVector3;
    interface IRayLibVector4;
    interface IRayLibRectangle;
    interface IRayLibMatrix;
    interface IRayLibCamera2D;
    interface IRayLibCamera3D;
    interface IRayLibRay;
    interface IRayLibTexture;
    interface IRayLibRenderTexture;
    interface IRayLibBoundingBox;
    interface IRayLibRayCollision;

    [
        uuid(8C02BF1F-FA49-4796-A634-FB591F749030),
        helpstring("RayLib Class")
    ]
        coclass RayLib
    {
        [default] interface IRayLib;
    };

    [
        uuid(B47D3FF5-7888-413F-BFCC-2F7550F68D18),
        helpstring("RayLib.Color Class")
    ]
        coclass RayLibColor
    {
        [default] interface IRayLibColor;
    };

    [
        uuid(09FB8F0F-AB6F-4AB5-9CF6-245CEC13A79B),
        helpstring("RayLib.Vector2 Class")
    ]
        coclass RayLibVector2
    {
        [default] interface IRayLibVector2;
    };

    [
        uuid(EFFF27AC-9E7D-433C-A2F2-82B0F52478E0),
        helpstring("RayLib.Vector3 Class")
    ]
        coclass RayLibVector3
    {
        [default] interface IRayLibVector3;
    };

    [
        uuid(A465B353-B852-4A1E-8A7E-910BE28C938E),
        helpstring("RayLib.Vector4 Class")
    ]
        coclass RayLibVector4
    {
        [default] interface IRayLibVector4;
    };

    [
        uuid(33E72FC4-1739-45ED-A7D4-F1A1821A35CC),
        helpstring("RayLib.Quaternion Class")
    ]
        coclass RayLibQuaternion
    {
        [default] interface IRayLibVector4;
    };

    [
        uuid(ED51BD5F-B9F8-49C6-A4B7-1AF251DA8CD6),
        helpstring("RayLib.Rectangle Class")
    ]
        coclass RayLibRectangle
    {
        [default] interface IRayLibRectangle;
    };

    [
        uuid(D08E2600-38D5-40CD-8923-3ADFB69876A7),
        helpstring("RayLib.Texture Class")
    ]
        coclass RayLibTexture
    {
        [default] interface IRayLibTexture;
    };

    [
        uuid(BD474986-F8E3-4EBA-BC23-C74AF876D450),
        helpstring("RayLib.RenderTexture Class")
    ]
        coclass RayLibRenderTexture
    {
        [default] interface IRayLibRenderTexture;
    };

    [
        uuid(7C96E97A-28F4-4499-BD32-E640687D434C),
        helpstring("RayLib.Texture2D Class")
    ]
        coclass RayLibTexture2D
    {
        [default] interface IRayLibTexture;
    };

    [
        uuid(7596E3C4-80A0-4827-ABDD-79DD78BFDC15),
        helpstring("RayLib.RenderTexture2D Class")
    ]
        coclass RayLibRenderTexture2D
    {
        [default] interface IRayLibRenderTexture;
    };

    [
        uuid(763865FF-7A3D-427E-9022-1FF9E5C991C6),
        helpstring("RayLib.Matrix Class")
    ]
        coclass RayLibMatrix
    {
        [default] interface IRayLibMatrix;
    };

    [
        uuid(D65CEE32-C161-49AE-878C-DC8899681000),
        helpstring("RayLib.Camera2D Class")
    ]
        coclass RayLibCamera2D
    {
        [default] interface IRayLibCamera2D;
    };

    [
        uuid(4AD5E4B2-354D-443C-936F-9EBDD623735D),
        helpstring("RayLib.Camera3D Class")
    ]
        coclass RayLibCamera3D
    {
        [default] interface IRayLibCamera3D;
    };

    [
        uuid(A852FCBB-18EB-4B39-85E5-19F51E96C3BC),
        helpstring("RayLib.Camera Class")
    ]
        coclass RayLibCamera
    {
        [default] interface IRayLibCamera3D;
    };

    [
        uuid(DE2DFA2C-F1F7-4FB4-A663-C3BFFC0806ED),
        helpstring("RayLib.BoundingBox Class")
    ]
        coclass RayLibBoundingBox
    {
        [default] interface IRayLibBoundingBox;
    };

    [
        uuid(66019F59-AA67-4250-8593-32E91A4C2B8B),
        helpstring("RayLib.RayCollision Class")
    ]
        coclass RayLibRayCollision
    {
        [default] interface IRayLibRayCollision;
    };

    [
        uuid(FEC4DDB5-CE85-4062-86DE-8853D9EFC3B2),
        helpstring("RayLib.Ray Class")
    ]
        coclass RayLibRay
    {
        [default] interface IRayLibRay;
    };
};
